package net.fionix.minima;

import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.os.Bundle;
import android.os.Environment;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.webkit.WebView;
import android.widget.Button;
import android.widget.Toast;

import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

public class ActivityTable extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_table);

        final WebView webView = (WebView) findViewById(R.id.webView1);
        webView.getSettings().setDisplayZoomControls(false);
        webView.getSettings().setBuiltInZoomControls(true);
        webView.getSettings().setUseWideViewPort(true);
        webView.setInitialScale(1);

        ArrayList<ClassTimetable> arrayListTimetable = ClassMinima.loadTimetable(getApplicationContext());
        ArrayList<ClassCourse> arrayListCourse = ClassMinima.loadCourse(getApplicationContext());

        String htmlHeader = "<!DOCTYPE html><html><head><meta charset=\"utf-8\"><title></title></head><body style=\"width: 1360px; padding: 50px;\"><style media=\"screen\">table,th,td {text-align: center;border: 1px solid black;border-collapse: collapse;}td {width: 120px;height: 75px;}th {height: 50px;}</style><table><tr style=\"background: #D3D3D3\"><th width=\"200px;\">Day</th><th colspan=\"2\">8.00am - 9.00am</th><th colspan=\"2\">9.00am - 10.00am</th><th colspan=\"2\">10.00am - 11.00am</th><th colspan=\"2\">11.00am - 12.00pm</th><th colspan=\"2\">12.00pm - 1.00pm</th><th colspan=\"2\">1.00pm - 2.00pm</th><th colspan=\"2\">2.00pm - 3.00pm</th><th colspan=\"2\">3.00pm - 4.00pm</th><th colspan=\"2\">4.00pm - 5.00pm</th><th colspan=\"2\">5.00pm - 6.00pm</th><th colspan=\"2\">6.00pm - 7.00pm</th><th colspan=\"2\">7.00pm - 8.00pm</th><th colspan=\"2\">8.00pm - 9.00pm</th><th colspan=\"2\">9.00pm - 10.00pm</th><th colspan=\"2\">10.00pm - 11.00pm</th></tr>";
        String htmlMonday = ClassMinima.generateTable("Monday", arrayListTimetable);
        String htmlTuesday = ClassMinima.generateTable("Tuesday", arrayListTimetable);
        String htmlWednesday = ClassMinima.generateTable("Wednesday", arrayListTimetable);
        String htmlThursday = ClassMinima.generateTable("Thursday", arrayListTimetable);
        String htmlFriday = ClassMinima.generateTable("Friday", arrayListTimetable);
        String htmlSaturday = ClassMinima.generateTable("Saturday", arrayListTimetable);
        String htmlSunday = ClassMinima.generateTable("Sunday", arrayListTimetable);
        String htmlHidden = "<tr><td colspan=\"31\" style=\"text-align: center; height:30px;\"><strong>Timetable generated by Minima</strong></td></tr><tr style=\"visibility:hidden;\"><td>Hidden</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr></table>";
        String htmlCourse = ClassMinima.generateCourseList(arrayListCourse);
        String htmlFooter = "</body></html>";

        String html = htmlHeader + htmlMonday + htmlTuesday + htmlWednesday + htmlThursday + htmlFriday + htmlSaturday + htmlSunday + htmlHidden + htmlCourse + htmlFooter;

        Toast.makeText(getApplicationContext(), "You can zoom by pinch in or out", Toast.LENGTH_SHORT).show();
        webView.loadData(html, "text/html", "UTF-8");

        Button buttonSaveAs = (Button) findViewById(R.id.button1);
        buttonSaveAs.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                // generate png
                Bitmap bitmap = Bitmap.createBitmap(webView.getWidth(), 720, Bitmap.Config.ARGB_8888);
                Canvas canvas = new Canvas(bitmap);
                webView.draw(canvas);

                // check for folder existence
                File folder = new File(Environment.getExternalStorageDirectory() + "/Minima");
                if (!folder.exists()) {
                    folder.mkdir();
                }

                // generate png file
                FileOutputStream outputStream;
                try {
                    String location = Environment.getExternalStorageDirectory() + "/Minima/minima_timetable_" + new SimpleDateFormat("yyyy_MM_dd_HH_mm_ss").format(new Date()) + ".png";
                    File file = new File(Environment.getExternalStorageDirectory() + "/Minima/", "minima_timetable_" + new SimpleDateFormat("yyyy_MM_dd_HH_mm_ss").format(new Date()) + ".png");
                    outputStream = new FileOutputStream(file);
                    bitmap.compress(Bitmap.CompressFormat.PNG, 100, outputStream);
                    outputStream.close();
                    Toast.makeText(getApplicationContext(), "Image saved at: " + location, Toast.LENGTH_SHORT).show();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }
}
